field: bacc9914-340e-463e-8d19-5345afda9138 # Body
fieldLayouts:
  3c8a9cfe-c7ca-4376-b915-a84169e7c8d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 75b10c33-7c59-49c8-b37b-7f0308f9a1be # Citation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79180745-0656-43ea-9d06-9c8a3588435f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 012e2658-c745-4e8f-a389-441590b2a56d # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d613cf01-e089-4d11-a9b4-6acaf5e8ce3b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fe88f204-2b51-41a6-b9cf-9eae5ba99135
        userCondition: null
fields:
  012e2658-c745-4e8f-a389-441590b2a56d: # Quote
    columnSuffix: iykqolhx
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: null
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  75b10c33-7c59-49c8-b37b-7f0308f9a1be: # Citation
    columnSuffix: kyiumkyq
    contentColumnType: text
    fieldGroup: null
    handle: citation
    instructions: null
    name: Citation
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: blockquote
name: Blockquote
sortOrder: 5
