field: bacc9914-340e-463e-8d19-5345afda9138 # Body
fieldLayouts:
  653e681f-a9d1-4dbd-8b9f-7b71f91c1557:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3d7b9ad6-60ed-437b-89e3-6a696cf736ed # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 048dae60-4d9b-49a3-bff4-6868cc480d8d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 238a3bb5-4746-4d83-b24d-d44691ad3d46
        userCondition: null
fields:
  3d7b9ad6-60ed-437b-89e3-6a696cf736ed: # Subtitle
    columnSuffix: boimvsah
    contentColumnType: text
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: subtitle
name: Subtitle
sortOrder: 2
