fieldLayouts:
  dc0495e8-bb76-4fb2-87ff-3a3e5b149e1a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 445356ec-bf51-465e-b57c-5445ad388f50
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4914a42f-3b7b-4f58-b2d8-7de139fa958c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9bb85d0-926f-4d90-be7d-e623f12398f2 # Topic Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 907b4500-d952-48a8-b1a2-4f18494473bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 408e1203-5e95-4d2c-ab8f-e1c921c03d8e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62d7bcb0-16d2-42a9-831e-9cc80bab4b5b # Topic Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: af178bb5-faa3-40c9-a198-33e107e02743
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1f05f85-09e9-4ea9-9948-6ad4a55357f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ebcbf2d-1720-44f4-9a2e-a9da74dab28e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7c04110d-edd0-48f9-a927-cc7f8af78b81
        userCondition: null
handle: banner
hasTitleField: true
name: Banner
section: 249bc4ae-d94e-454b-95df-7e56c57eff08 # Home Page
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
