fieldLayouts:
  712c960c-dba6-4db1-98f7-34647b95f0c2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d8efa791-22f7-49ca-9520-43a6a6d00c89
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 53c25122-b2df-44a3-a37f-6da54bc667eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98b83ad8-5c78-41bc-96aa-0b9aab19a2cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f0156e7-312f-4902-beb9-a14fefb28301
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62d7bcb0-16d2-42a9-831e-9cc80bab4b5b # Topic Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cc1424c-985d-4afe-9eb1-1e4f77b1cc53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bacc9914-340e-463e-8d19-5345afda9138 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70f8598a-b082-4c04-96f1-2309cc9c0286
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1be642dc-384b-4c76-88a0-df65cce5cde5
        userCondition: null
handle: blogpost
hasTitleField: true
name: 'Blog Post'
section: 8890c4af-24db-46a4-bdba-7c9733d4e525 # Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
