fieldLayouts:
  6dabdead-741e-4497-82f6-5ca784159152:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5212e492-42b7-4d63-84d1-83cd849cd90c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b49416db-8b5d-421e-a505-6e759b0363d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 200786b9-1f6b-4335-bdd0-e7b8facb7807
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae3c238-06e6-4e13-a49a-de1dbff1d4ff # Topic RichText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 91a6cd58-634a-4e0a-b173-d383dbebdcc8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67073150-6f06-44da-b21e-ee864be81dc7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d93e450e-6c12-484a-94af-fd5657fee890 # Topic Banner
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2f118db-e568-4fde-81bc-062ad3c3105e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0bd0adc7-bfca-4561-8875-408011247ee5
        userCondition: null
handle: category
hasTitleField: true
name: Category
section: 86243be3-8e67-464f-a760-6ee3eaebbb51 # Wine Category
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
