fieldLayouts:
  ebfd2452-5adf-4007-b78c-8f941c8325bc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0b14c98d-5e77-4479-b540-e526e9d86e64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47d27973-b000-4469-9d76-cb26214ddb90
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fd5e667-b685-4fc7-b5cf-1e59ba970d0d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae3c238-06e6-4e13-a49a-de1dbff1d4ff # Topic RichText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5e3df3b-1648-4523-ad94-0f9f3030b0d3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0f2e3872-ff0f-46c4-a2c2-aa1a2721e160
        userCondition: null
handle: contact
hasTitleField: true
name: 'Contact Us'
section: 2dfdcf51-6d59-41c7-8d01-f23a81e7b211 # Contact Us
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
