fieldLayouts:
  647476e0-b3d7-4e0f-951b-29e7747ab7a5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96bf9dec-c263-4fdf-b128-f7ec4b1e3426
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bca9a09b-e6d9-4142-a9e1-9a15139178c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9bb85d0-926f-4d90-be7d-e623f12398f2 # Topic Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f381257-1b48-4efd-a194-16a1debfecdd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a94f5dd-2cb1-4aa9-8b56-23a7c2c8ca23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e7ef90d-9a51-4c7e-be27-8aef41a83e31
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62d7bcb0-16d2-42a9-831e-9cc80bab4b5b # Topic Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b545a93-8ef3-41af-9043-6f3537a2bf37
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ed032820-4195-4790-a908-b6eb9974f33c
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 05418c21-53f8-4f73-9b54-63dff2e49d7d # Club
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
