fieldLayouts:
  e6f0c7c7-a3ae-4439-ad1a-6b6b8af7e8dd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e0693d0-093f-405e-84e5-4e59e432ca92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ee566788-59f7-4ea0-ae16-a2b1bc3811b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9bb85d0-926f-4d90-be7d-e623f12398f2 # Topic Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a57313-aa19-49f3-b74a-6b381dce192b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ad60cc2-155a-4041-8609-e32399ba680f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b46d7dea-e338-4678-b934-d4efa3058534
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62d7bcb0-16d2-42a9-831e-9cc80bab4b5b # Topic Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c0096aaa-1f06-4e9f-b077-f01e1ef1f65a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da7bbb73-08b6-4cd9-b990-474b0ea12128
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: b92b198b-8053-4363-a3cd-224ad4867fed # Vineyards
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
