fieldLayouts:
  9eeaaf23-578e-4ba4-b23e-a9e8ae95d47f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: df4868e6-9dfc-4c22-b14f-e8283f7db42b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fd63e9c-074f-44f6-8f17-439ca1298bd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9bb85d0-926f-4d90-be7d-e623f12398f2 # Topic Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eaa7fba-dc0c-4c56-a05e-222ddc0a8dd3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 798e802d-4f4a-49f7-869f-2b0db788ddd9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4b9326e-6975-4bf9-b518-362be7b45384
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bacc9914-340e-463e-8d19-5345afda9138 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf3e3f79-e2e3-441e-8827-7b43e047a63e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2f8ce486-b71f-4c0d-8955-38d3b19321b6
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 024cc291-626a-44bd-8733-7aa26557b87d # About Us
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
