fieldLayouts:
  17ed831e-fb24-42b7-a44a-ada04f84b06f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d63d3212-3230-4e2f-a94b-901a7f72d6e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c5926a3-48fe-49ae-8fdb-809e7f346a6a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9bb85d0-926f-4d90-be7d-e623f12398f2 # Topic Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f195411-0f5e-4542-8944-ea95ea81975a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cca2fcc0-371d-41aa-87e7-079777f84475
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa8a7b71-cec2-4fdf-8d05-0d4e15b11530
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c779ce8d-8c31-4f64-a04c-206ba77d3a8a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1a11654a-bd56-48e2-aa73-ecfbf2863fb6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62d7bcb0-16d2-42a9-831e-9cc80bab4b5b # Topic Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96c02c61-566d-4fff-b6d5-fcebf331fbec
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1f05f85-09e9-4ea9-9948-6ad4a55357f8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68d5a6d3-7f49-4a82-b0ec-cd36fa40fb31
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03f85123-db18-408b-949f-306479d738ba
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 249bc4ae-d94e-454b-95df-7e56c57eff08 # Home Page
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
