fieldLayouts:
  5002ca05-0dbf-4a29-816c-60feca340a85:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8e82cca6-36c8-42dc-8317-9048f77fc7b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fa174cf-9834-4e3c-9714-9b759a663dfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f1d36ca-8236-440e-8360-ba876acd4ef1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2661a5d-1997-45f1-9708-3dc2ba7d8731
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae3c238-06e6-4e13-a49a-de1dbff1d4ff # Topic RichText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b13ecda1-fcea-4adf-8239-72b79258fb12
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e794cb6c-d202-411c-b8b9-4dda6370f449
        userCondition: null
handle: error404
hasTitleField: true
name: '404 Error'
section: 4886d20d-f062-429c-bc59-31469fb46025 # 404 Error
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
