fieldLayouts:
  1add30c4-7063-4755-9666-4a82934b2b0f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a1dad1e4-fdb5-4a69-8b3a-7e38dbfec5b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e88b6eff-e6b3-4a5f-8db7-fcf54a8e9c57 # Site Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36f35b68-7c84-446e-8cbc-f99502176252
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5913033f-7b45-4065-bcd2-5188d9764973 # Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1908edf-2aed-412c-bf26-e7200b6544f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b210e6df-b6ce-436e-8b65-10f838522fff # Global Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 123af25e-1071-4bb9-81f1-5f332d94f61f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 411295fb-bfb8-48c5-ae52-42fb9dda0fb1
        userCondition: null
handle: globalHeader
hasTitleField: false
name: 'Global Header'
section: 63e5acce-34c9-455e-8914-3b92a6b87c5b # Global Header
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
