fieldLayouts:
  afc2a977-8a0e-46db-8166-cc068f993861:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6c527385-f7f9-4422-8cd7-95cebfd3aa32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 94f6487d-fdb2-45eb-b931-98719e143dfb
        userCondition: null
handle: region
hasTitleField: true
name: Region
section: b92b198b-8053-4363-a3cd-224ad4867fed # Vineyards
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
