fieldLayouts:
  1153aee6-6abb-41c0-a895-f0372fee13b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 35b6d73d-b83c-4c09-b568-b0c0f67b5c96
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a56eb0ac-1782-43c7-8016-b32ceaeb8438
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17eba7e5-de68-4e0b-981e-578dfee925fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae3c238-06e6-4e13-a49a-de1dbff1d4ff # Topic RichText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc636035-96b5-475c-9830-d9c29c98cf36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e90a51a-954f-440f-a846-0dd275b1026e
        userCondition: null
handle: shipping
hasTitleField: true
name: Shipping
section: 80d329e7-62c4-4f24-b717-fbb1dc37342f # Shipping
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
