fieldLayouts:
  9acf8e35-0c35-436c-b171-71134bb4f008:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 95fb8dc7-e8fc-4579-a9e7-799b48950055
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8c51f1b8-451f-41d5-b139-f9d030efcf45 # Topic Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0674954-bd76-42d7-be36-847ef94b6a27
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4e67ca40-b001-4a5e-b820-0843dca449a5 # Topic Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f48e916c-2d05-4076-9d82-b5fb4ba5feac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e38ee93c-6ae1-447f-8913-bc5d8a542ff5 # Topic Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1263abf3-4e6e-4756-a1ec-b9f448a12d92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3ae3c238-06e6-4e13-a49a-de1dbff1d4ff # Topic RichText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d01e7812-af16-4f7a-8360-4d8f47daece7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bf4bad99-4149-4a43-82cc-2a710fedd6a7
        userCondition: null
handle: terms
hasTitleField: true
name: 'Terms of Use'
section: 5b945092-b448-483b-b427-58216f9f3a5b # Terms of Use
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
