fieldLayouts:
  0e9ca3f2-fda2-4322-8359-4def384e7f4b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9ab588a0-62da-4fbe-b5bb-0a2929a1a263
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c84cdcce-576f-49a9-8e6f-ac5071a2fa83
        userCondition: null
handle: wineType
hasTitleField: true
name: Varietal
section: ca1c4ea1-3384-4601-87d5-bbd4103dd286 # Wines
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
