fieldLayouts:
  9f739195-b405-4ac9-856a-5096414e0de9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 641798d8-6df1-4342-ac9c-1c45fb513f73
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2694eaad-966f-429f-be1b-02ae779300b8 # Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62490069-45c5-4ca1-be2f-f7cb4c25fbed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41fd9888-75c5-40aa-96c0-8cf35141454b
        userCondition: null
fs: siteImages
handle: siteImages
name: 'Site Images'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
