columnSuffix: zhmiprpa
contentColumnType: text
fieldGroup: c8511db1-6c85-4a7b-883b-eb8283f3660d # Footer
handle: copyright
instructions: null
name: Copyright
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
