columnSuffix: null
contentColumnType: string
fieldGroup: 2f015bac-ca00-4129-9e30-45fc97b904fa # Common
handle: vineyardWines
instructions: null
name: 'Vineyard Wines'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Wines from Vineyard'
  showSiteMenu: true
  sources:
    - 'section:ca1c4ea1-3384-4601-87d5-bbd4103dd286' # Wines
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
