fieldLayouts:
  65228fbd-acd8-417d-b760-e5e3d4afd9bd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6014ea73-e0f0-4cd4-a2ac-eff43e74101f # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b98db77-0ea3-448a-b781-7d68e35373a0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a527be69-82a9-462e-adaa-0b5958be9ce0 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e03beaf-f7ec-41a8-9df5-faae89f23d52
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 48b6fa0b-00ba-40c4-8d81-7a4cd595e96e # Icon Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88e1b414-f9d1-475c-869c-3bdea867a7da
            userCondition: null
            warning: null
            width: 100
        name: Fields
        uid: e367d795-140c-4ad3-a31b-3d89acf88099
        userCondition: null
handle: footer
name: Footer
sortOrder: 2
