defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: topics/_entry
    uriFormat: 'topics/{slug}'
structure:
  maxLevels: null
  uid: 90832234-6171-48e4-8b29-a253881a5fc5
type: structure
