defaultPlacement: end
enableVersioning: true
handle: ourWines
name: 'Our Wines'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: ourwines/_entry
    uriFormat: ourwines
structure:
  maxLevels: null
  uid: 1c239ee9-df20-4cfe-b646-1d8518988bb8
type: structure
