defaultPlacement: end
enableVersioning: true
handle: team
name: Team
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: 'team/{slug}'
structure:
  maxLevels: null
  uid: f1406f7c-d539-4ce4-899c-f6060e58c1a7
type: structure
