defaultPlacement: end
enableVersioning: true
handle: vineyards
name: Vineyards
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: 'vineyards/{slug}'
structure:
  maxLevels: null
  uid: 76c3c0fd-4621-4aa0-ab50-211892d08b2f
type: structure
