defaultPlacement: end
enableVersioning: true
handle: wineCategory
name: 'Wine Category'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: ourwines/_entry
    uriFormat: 'ourwines/{slug}'
structure:
  maxLevels: null
  uid: 6b8052e8-c9f6-46d4-b743-c163fd59a83d
type: structure
