defaultPlacement: end
enableVersioning: true
handle: wines
name: Wines
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  ba700213-75f7-4cac-90d0-83101e67f7db: # Soma Cellars
    enabledByDefault: true
    hasUrls: true
    template: entry
    uriFormat: 'wines/{slug}'
structure:
  maxLevels: null
  uid: 44217fb4-54f1-4779-b747-4b51ad17e3df
type: structure
